version: '3.8'

services:
  keycloak:
    image: keycloak/keycloak:26.0
    container_name: marketplace-keycloak-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak_user
      - KC_DB_PASSWORD=keycloak_pass
      - KC_HOSTNAME=localhost
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - marketplace-network

  postgres:
    image: postgis/postgis:17-3.4
    container_name: marketplace-postgres-dev
    environment:
      - POSTGRES_DB=marketplace_dev
      - POSTGRES_USER=marketplace_user
      - POSTGRES_PASSWORD=marketplace_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - marketplace-network

  keycloak-postgres:
    image: postgres:17
    container_name: keycloak-postgres-dev
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak_user
      - POSTGRES_PASSWORD=keycloak_pass
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - marketplace-network

  redis:
    image: redis:7-alpine
    container_name: marketplace-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes
    networks:
      - marketplace-network

  elasticsearch:
    image: elasticsearch:8.15.0
    container_name: marketplace-elasticsearch-dev
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_dev_data:/usr/share/elasticsearch/data
    networks:
      - marketplace-network

volumes:
  postgres_dev_data:
  keycloak_postgres_data:
  redis_dev_data:
  elasticsearch_dev_data:

networks:
  marketplace-network:
    driver: bridge